# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-0ea5fee4-44a8-478e-b412-c2cfcb82d8d7";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-0ea5fee4-44a8-478e-b412-c2cfcb82d8d7".device = "/dev/disk/by-uuid/0ea5fee4-44a8-478e-b412-c2cfcb82d8d7";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D77E-3009";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-eed7b2e8-1aa2-4ebd-be64-f30def158418"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
